### ISSUE TITLE
Images without a path throw error when passed through lazy filter

### ISSUE THREAD

**Issue by Mosnar** [mmikkel/Retcon-Craft#21]
I imported several hundred old blog posts and discovered that some of them had some malformed img tags where the `src` didn't include a path, only the host. This causes retcon to throw an exception, as it expects a path to exist.

This is the html that was being processed:
```
<img class="img-responsive fr-dib fr-fin" src="https://site.com" data-image="jb2p69ar8k3c">
```

And the error:
```
yii\base\ErrorException: Undefined index: path in /home/forge/site.com/vendor/mmikkel/retcon/src/library/RetconHelper.php:298
Stack trace:
#0 /home/forge/site.com/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/forge/site...', 298)
#1 /home/forge/site.com/vendor/mmikkel/retcon/src/library/RetconHelper.php(298): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/home/forge/site...', 298, Array)
#2 /home/forge/site.com/vendor/mmikkel/retcon/src/services/RetconService.php(262): mmikkel\retcon\library\RetconHelper::getImageDimensions(Object(DOMElement))
#3 /home/forge/site.com/vendor/mmikkel/retcon/src/services/RetconService.php(70): mmikkel\retcon\services\RetconService->lazy('<p><a href="htt...')
#4 /home/forge/site.com/storage/runtime/compiled_templates/ca/ca4e1f0aff2ff0f8d69735d3e3bb6e033632339baf61df7a3d191d8c08da5d96.php(44): mmikkel\retcon\services\RetconService->retcon('<p><a href="htt...', 'lazy')
#5 /home/forge/site.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_d11ff7e2785393acc074b164cf169231f5d14d572415312ea95d3f679c65568f->doDisplay(Array, Array)
#6 /home/forge/site.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /home/forge/site.com/storage/runtime/compiled_templates/d3/d328be4dc03dd9eb6c88957b529d173aebba89c74c886766317a55f8d915a72f.php(103): Twig\Template->display(Array)
#8 /home/forge/site.com/vendor/twig/twig/src/Extension/CoreExtension.php(1105): __TwigTemplate_aab90291d6c720e19ce99168187e187403ddd4124a5aee82e5fc23cb0c78b4dc->macro_make(Object(craft\elements\db\MatrixBlockQuery))
#9 /home/forge/site.com/storage/runtime/compiled_templates/80/809db507607601f66dc09bc8c61207c7ff3bd2ee7d5282503cf96f31856dc72d.php(125): twig_call_macro(Object(__TwigTemplate_aab90291d6c720e19ce99168187e187403ddd4124a5aee82e5fc23cb0c78b4dc), 'macro_make', Array, 35, Array, Object(Twig\Source))
#10 /home/forge/site.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_47b6ab617b3533417ed8cc101916278c969abf85ea0681ebe67dce838680ae76->block_content(Array, Array)
#11 /home/forge/site.com/storage/runtime/compiled_templates/8f/8fb9132364cb71c3ed0a881a727651377c507a7e11028482446a65a37f229727.php(99): Twig\Template->displayBlock('content', Array, Array)
#12 /home/forge/site.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_63bb89473834178ac27bd792973c77e6732e223e2a7c3f8408967b701c8573a6->block_bodyHtml(Array, Array)
#13 /home/forge/site.com/storage/runtime/compiled_templates/f6/f61ab52ba8b025842cee120d9fdadc10298709e31c2e765374e63244ed32311f.php(179): Twig\Template->displayBlock('bodyHtml', Array, Array)
#14 /home/forge/site.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c33364591d1e3c05a875145f64e114421d1cced9fe137a315d9cc8fe9ca8a0ea->block_bodyContent(Array, Array)
#15 /home/forge/site.com/storage/runtime/compiled_templates/56/569520411ae1133aa715b8807d8f7892faed53eabd470b3eddf4f254773bfda4.php(91): Twig\Template->displayBlock('bodyContent', Array, Array)
#16 /home/forge/site.com/vendor/twig/twig/src/Template.php(184): __TwigTemplate_ae9ed2e94e04f5af539fb46353d24bd583482c24334c553a361f42d33af722bc->block_htmlPage(Array, Array)
#17 /home/forge/site.com/storage/runtime/compiled_templates/2a/2a57971723b7077052ffec1040c282fda1debc9ec11623ba71df3dd77962da44.php(70): Twig\Template->displayBlock('htmlPage', Array, Array)
#18 /home/forge/site.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_4407ed3d4c6bf91fe238f5bd82807316b3a70e2e27597702aa6d9e3c94fddf5c->doDisplay(Array, Array)
#19 /home/forge/site.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /home/forge/site.com/storage/runtime/compiled_templates/56/569520411ae1133aa715b8807d8f7892faed53eabd470b3eddf4f254773bfda4.php(50): Twig\Template->display(Array, Array)
#21 /home/forge/site.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ae9ed2e94e04f5af539fb46353d24bd583482c24334c553a361f42d33af722bc->doDisplay(Array, Array)
#22 /home/forge/site.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /home/forge/site.com/storage/runtime/compiled_templates/f6/f61ab52ba8b025842cee120d9fdadc10298709e31c2e765374e63244ed32311f.php(53): Twig\Template->display(Array, Array)
#24 /home/forge/site.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c33364591d1e3c05a875145f64e114421d1cced9fe137a315d9cc8fe9ca8a0ea->doDisplay(Array, Array)
#25 /home/forge/site.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /home/forge/site.com/storage/runtime/compiled_templates/8f/8fb9132364cb71c3ed0a881a727651377c507a7e11028482446a65a37f229727.php(52): Twig\Template->display(Array, Array)
#27 /home/forge/site.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_63bb89473834178ac27bd792973c77e6732e223e2a7c3f8408967b701c8573a6->doDisplay(Array, Array)
#28 /home/forge/site.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /home/forge/site.com/storage/runtime/compiled_templates/80/809db507607601f66dc09bc8c61207c7ff3bd2ee7d5282503cf96f31856dc72d.php(55): Twig\Template->display(Array, Array)
#30 /home/forge/site.com/vendor/twig/twig/src/Template.php(407): __TwigTemplate_47b6ab617b3533417ed8cc101916278c969abf85ea0681ebe67dce838680ae76->doDisplay(Array, Array)
#31 /home/forge/site.com/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#32 /home/forge/site.com/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#33 /home/forge/site.com/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#34 /home/forge/site.com/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#35 /home/forge/site.com/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('_sections/blog/...', Array)
#36 /home/forge/site.com/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('_sections/blog/...', Array)
#37 /home/forge/site.com/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('_sections/blog/...', Array)
#38 /home/forge/site.com/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('_sections/blog/...', Array)
#39 [internal function]: craft\controllers\TemplatesController->actionRender('_sections/blog/...', Array)
#40 /home/forge/site.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#41 /home/forge/site.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#42 /home/forge/site.com/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#43 /home/forge/site.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#44 /home/forge/site.com/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#45 /home/forge/site.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#46 /home/forge/site.com/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#47 /home/forge/site.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#48 /home/forge/site.com/web/index.php(17): yii\base\Application->run()
#49 {main}
```

Ideally, the exception should be caught and logged rather than breaking the site.

**Comment by mmikkel** [comment]
Thanks for reporting, @Mosnar. I concur that the exception should be logged and not thrown – will get a fix out ASAP :)

**Comment by mmikkel** [comment]
Fixed in Retcon v. 2.1.0.
